### ISSUE TITLE
Not Working Anymore for Free Listener (Solved)

### ISSUE THREAD

**Issue by DankiestCitra** [lethak/digitally_imported_userscript#75]
DI ended their Free Listener program, so now its not working at all.
Is there any way to restore the previous Free Listener functionality somehow?

**Comment by lethak** [comment]
If the change is just client side and cosmetic this will be no different than before.
However, if they engineered the change properly, there will be no way to bypass.

At this point I had zero chance to look it up and will not hazard a guess. But in due time I will know.

**Comment by lethak** [comment]
Just a quick update to tell you access to audio source is still allowed by their servers, so my early guess is that some form of client side bypass might just be possible.

**Comment by Quqas** [comment]
at the moment it works normally only in incognito.
in normal mode, regardless of whether you are logged into your account - it immediately requires a paid account.
somewhere there is an indestructible cache stored (F12\application\Storage does not help at all)

------------------------
на текущий момент нормально работает только в инкогнито.
в нормальном режиме вне зависимости от входа в аккаунт  - сразу требует платного аккаунта.
где-то хранится неубиваемый кэш (F12\aplication\Storage никак не помогает)

**Comment by lethak** [comment]
> at the moment it works normally only in incognito

### Workaround

It will work in incognito for 3600 seconds while logged out. You can try to close/reopen the incognito browser and it may work again for 3600 seconds.

This is a current workaround to the problem actually, while far from a good solution of course.

It is worth noting existing premium user have no broken feature in the current site and script version as this change only affect free listeners.

### Soon

I quickly peaked to the code changes, and I can say they built this new lock system on top of the existing channel lock system.
It is actually the same system they modified, and since its only a cosmetic change, I am confident the userscript can be updated when ready.

**Comment by lethak** [comment]
Fixed with [v2025.3.146](https://github.com/lethak/LTKDIFMU-userscript/releases/tag/v2025.3.146)

**Comment by DankiestCitra** [comment]
> Fixed with [v2025.3.146](https://github.com/lethak/LTKDIFMU-userscript/releases/tag/v2025.3.146)

You are a God among men.
The hero we need but not the one we deserve!

**Comment by dzejsonista** [comment]
> Fixed with [v2025.3.146](https://github.com/lethak/LTKDIFMU-userscript/releases/tag/v2025.3.146)

I love you! :)

**Comment by SebastianRasch** [comment]
@lethak They changed something again and it's not working anymore. Like last time, it still works in incognito mode (but I can't log in there). 
Removed the overlay with an adblocker (di.fm###modal-region) but still can't click on play in public mode.

**Comment by lethak** [comment]
> [@lethak](https://github.com/lethak) They changed something again and it's not working anymore. Like last time, it still works in incognito mode (but I can't log in there). Removed the overlay with an adblocker (di.fm###modal-region) but still can't click on play in public mode.

Nothing appears to have changed and the issue is probably on your end.

Tampermonkey requires developer mode enabled since manifest apiv3 was forced onto chromium users recently.

If this is not it, try with Firefox as it have endless support for manifest apiv2

If nothing works, please open a new issue with all the version details

**Comment by SebastianRasch** [comment]
Yeah weird, now it works again and the overlay doesn't block playback anymore. Must've been a hickup.
